AppCoder/urls.py
from django.contrib import admin
from django.urls import path
from AppCoder import views
from AppCoder.views import *
from django.contrib.auth.views import LogoutView
###########





urlpatterns = [
    
    path("",inicio, name="beginning"),
    
    
    path("formu1/", formulario1, name = "FormularioDatos"),
    path("busquedaDB/", busquedaDB, name= "email"),
    path("resultados/", resultados, name= "ResultadosBusqueda"),
    path("aboutme/", about, name= "AboutMe"),
    #Crud de Data usando Clases
    
    path("data/list/", views.ListaData, name="DataLeer"),
    path("data/<int:pk>", DetalleData.as_view(), name="DataDetalle"),
    path("data/crear/", CrearData.as_view(), name="DataCrear"),
    path("data/editar/<int:pk>/", ActualizarData.as_view(), name="DataEditar"),
    path("data/borrar/<int:pk>/", BorrarData.as_view(), name="DataBorrar"),
    
    #Login
    path("accounts/login/", inicioSesion, name="Login"),
    
    #Registro
    path("accounts/singup/", registro, name="SignUp"),

    #Logout
    path("logout/", LogoutView.as_view(template_name= "AppCoder/logout.html"), name="Logout"),



    #EditarUser
    path("accounts/profile/", editarUsuario, name="EditarUsuario"),

    #Subir Imagenes
    path("agregarImagen/", views.agregarImagen, name="AgregarImagen"),





]

ProyectoCoder/urls.py
from django.contrib import admin
from django.urls import path, include
from AppCoder.views import *


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
   path("AppCoder/", include("AppCoder.urls")),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppCoder/models.py
import email
from email.mime import image
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User
# Create your models here.




    
class Data(models.Model):
    
    def __str__(self):
        return f"Nombre: {self.nombre} - Email: {self.email} - Phone: {self.phone} - Imagen: {self.imagen}"
    
    
    nombre = models.CharField(max_length=60)
    email = models.EmailField()
    phone = models.IntegerField()
    imagen = models.ImageField(upload_to="imagen", null=True, blank=True)
    
    
class Avatar(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)
    
    class Meta:
        verbose_name = "Avatar"
        verbose_name_plural = "Avatares"
        
        

class Imagenes(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="imagenes", null=True, blank=True)
    
    
    

AppCoder/forms.py
from dataclasses import fields
from django import forms
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User

from AppCoder.models import Avatar, Data

class FormularioDatos(forms.ModelForm):  #relacionada a models tabla Data

    class Meta:
        model = Data
        fields = ['nombre', 'email', 'phone', 'imagen']


class UsuarioRegistro(UserCreationForm):
    
    email = forms.EmailField()
    password1 = forms.CharField(label = "Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label = "Repetir Contraseña", widget=forms.PasswordInput)
    
    class Meta:
        
        model = User
        fields =["username", "email", "first_name","last_name", "password1", "password2"]
        
       
       
class FormularioEditar(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label = "Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label = "Repetir Contraseña", widget=forms.PasswordInput) 
    
    class Meta:
        
        model = User
        fields =[ "email", "first_name","last_name", "password1", "password2"]
        
        
        
class ImagenesFormulario(forms.ModelForm):
    
    class Meta:
        model = Avatar
        fields = [ 'user', 'imagen']
        
class AvatarFormulario(forms.ModelForm):
    
    class Meta:
        model = Avatar
        fields = [ 'user', 'imagen']

AppCoder/views.py
import email
from http.client import HTTPResponse
from unicodedata import name
from django.shortcuts import render
from django.http import HttpResponse
from AppCoder.models import * 
from AppCoder.forms import * # Imports forms djnago
from django.views.generic import ListView 
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView


# Login
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, User
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin #Login para clases
from django.contrib.auth.decorators import login_required #Login para vistas
#######


def inicioSesion(request):
    
    if request.method == "POST":
    
        form = AuthenticationForm(request, data = request.POST)

        if form.is_valid():
            
            usuario = form.cleaned_data.get("username")
            contra = form.cleaned_data.get("password")
            
            user = authenticate(username=usuario, password=contra)
            
            if user:
                
                login(request, user)
                
                return render(request, "AppCoder/inicio.html", {"mensaje":f"{user}"})
        
        else:
            return render(request, "AppCoder/inicio.html", {"mensaje":"Datos incorrectos."})


    else:
        form = AuthenticationForm()

    return render(request, "AppCoder/login.html", {"formulario": form})








def registro(request):
    
    if request.method == "POST":
        
        form = UsuarioRegistro(request.POST)
        
        if form.is_valid():
            
            username = form.cleaned_data["username"]
            form.save()
            return render(request, "AppCoder/inicio.html", {"mensaje":"Usuario creado"})

    else:
        form = UsuarioRegistro()
    
    return render(request, "AppCoder/registro.html", {"formulario": form})








@login_required
def editarUsuario(request):
    
    usuario = request.user
    
    if request.method == "POST":
        
        form = FormularioEditar(request.POST)
        
        if form.is_valid():
            
            info = form.cleaned_data
            
            usuario.email = info["email"]
            usuario.set_password(info["password1"])
            usuario.first_name = info["first_name"]
            usuario.last_name = info["last_name"]
            
            usuario.save()
            
            return render(request, "AppCoder/inicio.html")
    
    else: 
        form = FormularioEditar(initial={
            "email": usuario.email,
            "first_name": usuario.first_name,
            "last_name": usuario.last_name,
            
        })
    return render(request, "AppCoder/editarPerfil.html", {"formulario": form, "usuario": usuario})

                                                                             
                                         
                                         





# Create your views here.

# HTML

def inicio(request): #inicio.html  - muestra todo
    return render(request, "AppCoder/inicio.html")


def about(request): #aboutme.html  - muestra todo
    return render(request, "AppCoder/aboutme.html")









# FORMULARIO ------------------------------------------

#Formulario Forms y models 
@login_required
def formulario1(request):
    if request.method == "POST": # Si le doy al boton
        
        formulario = FormularioDatos(request.POST)
        
        if formulario.is_valid(): # comprobar que no haya errores    
            info = formulario.cleaned_data
            DataF = Data(nombre=info["nombre"], email=info["email"], phone=info["phone"], imagen=info["imagen"]) #Lee la info de las cajas de texto
            DataF.save()
            return render(request, "AppCoder/Inicio.html")
    else:
        formulario = FormularioDatos() #mostrar el formulario vacio    
    
    return render(request, "AppCoder/formu1.html", {"form1": formulario })  # Entro al ulr y me muestra una plantilla







# Busqueda Database ------------------------------------------

def busquedaDB(request):
    
    return render(request, "AppCoder/Inicio.html")

def resultados(request):
    
    if request.GET["email"]:
        
        Email = request.GET["email"]
        datos = Data.objects.filter(email__icontains=Email)
#       datos = Data.objects.filter(email__iexact=Email)
        return render(request, "AppCoder/Inicio.html", {"datos": datos,"email":Email,"datos": datos} )
    else:
        
        respuesta = "No enviaste datos."
    
    return HttpResponse(respuesta)














# -------------------------------------------------------




# CRUD con clases

def ListaData(request):
    data = Data.objects.all()

    return render (request, "AppCoder/data_list.html", {"data": data })
    
class DetalleData(LoginRequiredMixin, DetailView):
    model = Data
    

class CrearData(LoginRequiredMixin, CreateView):
    model = Data
    success_url = "/AppCoder/data/list"
    fields = ["nombre", "email", "phone", "imagen" ]



class ActualizarData(LoginRequiredMixin, UpdateView):
    model = Data
    success_url = "/AppCoder/data/list"
    fields = ["nombre", "email", "phone", "imagen" ]



class BorrarData(LoginRequiredMixin, DeleteView):
    model = Data
    success_url = "/AppCoder/data/list"
    fields = ["nombre", "email", "phone", "imagen" ]
    
    
    
    
    ########################################
    
    
@login_required
def agregarAvatar(request):
    
    if request.method=="POST":
        form = AvatarFormulario(request.POST, request.FILES)
        
        


@login_required
def agregarImagen(request):
    
    if request.method=="POST": #presionar el boton
        
        miFormulario = ImagenesFormulario(request.POST, request.FILES)
        
        if miFormulario.is_valid(): # comprobar que no haya errores    
            
            info = miFormulario.cleaned_data
            
           # avatar = Imagenes(user=request.user, imagen=info['imagen'])
            avatar = Imagenes(user=info['user'], imagen=info['imagen'])

            avatar.save()
            
            return render(request, "AppCoder/Inicio.html")
    else:
        miFormulario = ImagenesFormulario() #mostrar el formulario vacio    
    
    return render(request, "AppCoder/AgregarIMG.html", {"form": miFormulario })  # Entro al ulr y me muestra una plantilla

AppCoder/templates/appcoder/AgregarIMG.html
{% extends "AppCoder/padre.html" %}
{% load static %}


{% block titulo %}
<h1>Subir imagen<h1>

    <form action="" method="POST"> {% csrf_token %}
        
        <table>    
            {{form.as_table}}

        </table>


       <div> 
        <input type="submit" value= "Subir", style="color:purple" >
       </div>

 </form>

{% endblock %}

{% block titulo2 %}



{% block descripcion %} 

<form action="/AppCoder/resultados/" method="GET"> {% csrf_token %}

    <h2> Busqueda </h2>
   <input type="text" name = "email" id ="email" >
  
    <input type="submit" value= "Buscar">

</form> 

{% endblock %}


<p>Estamos buscando: {{email}} </p>

{% for x in datos %}
    <p> Nombre: {{x.nombre}} --- Email: {{x.email}} ---- Phone: {{x.phone}}  </p>
{% endfor %}


{% endblock %}

AppCoder/templates/appcoder/aboutme.html
{% extends "AppCoder/padre.html" %}
{% load static %}


{% block titulo %}
<h1>AboutMe de mi pagina<h1>
<p> Carga personas en la base de datos desde formularios</p>


       

{% endblock %}

{% block titulo2 %}



{% block descripcion %} 

<form action="/AppCoder/resultados/" method="GET"> {% csrf_token %}

    <h2> Busqueda </h2>
   <input type="text" name = "email" id ="email" </p>
  
    <input type="submit" value= "Buscar">

</form> 

{% endblock %}


<p>Estamos buscando: {{email}} </p>

{% for x in datos %}
    <p> Nombre: {{x.nombre}} --- Email: {{x.email}} ---- Phone: {{x.phone}}  </p>
{% endfor %}


{% endblock %}

AppCoder/templates/appcoder/data_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <form action="" method="POST"> {%csrf_token %%}

        <p> ¿Borrar?</p>



        <input type="submit" value="Delete">


</body>
</html>

AppCoder/templates/appcoder/data_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

    <p>Nombre: {{data.nombre}}</p>
    <p>Email: {{data.email}} </p>
    <p>Phone: {{data.phone}} </p>
    <p>Imagen: {{data.imagen}} </p>

    <a href="{% url 'DataLeer'%}"> Regresar </a>
</body>
</html>

AppCoder/templates/appcoder/data_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <form action="" method="POST"> {%csrf_token %%}

        {{form.as_p}}

        <input type="submit" value="Enviar">


</body>
</html>

AppCoder/templates/appcoder/data_list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'AppCoder/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppCoder/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body> 
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">

                <a class="navbar-brand" href="{% url 'beginning' %}">Inicio</a>
                            {% if request.user.is_authenticated %} 
                            <a class="navbar-brand" href="{% url 'DataLeer' %}">Lista</a>
                            <a class="navbar-brand" href="{% url 'AboutMe' %}">AboutMe</a>
                            <a class="navbar-brand" href="{% url 'FormularioDatos' %}">Formularios</a>
                            <a class="navbar-brand" href="{% url 'AgregarImagen' %}">Imagenes</a>

                            {% endif%}

              

                {% if request.user.is_authenticated %} 

                    <p>Hola {{user.first_name}}

                    {% with user.avatar_set.first as miAvatar %}
                    
                    {%if miAvatar %}
                        
                        <img src="{{miAvatar.imagen.url}}" alt="No encontro" style="max-width: 40px ;">

                    {% endif%}



                    {%endwith%}

                    <a class="btn btn-primary" href={% url 'EditarUsuario'%} >Editar Usuario</a>
                    <a class="btn btn-primary" href={% url 'Logout' %} >Logout</a>
                
                {% else %}
                    <a class="btn btn-primary" href={% url 'Login' %} >Iniciar Sesión</a>
                    <a class="btn btn-primary" href={% url 'SignUp' %} >Registrarse</a>
                
                {% endif %}
            </div>
        </nav>

<h2> Data Models Información </h2>

{% for x in data %}
    <ol>
    <h4>Email: {{x.email}}</h4>

    <img src="{{x.imagen}}" alt="No hay imagen.">


    <button><a href= "{% url 'DataDetalle' x.id %}"> Ver </a></button>
    <button> <a href= "{% url 'DataEditar' x.id %}"> Editar </a></button>
    <button> <a href= "{% url 'DataBorrar' x.id %}"> Borrar </a></button>

    </ol>
{%endfor%}



<br>
<div>
<button>
<a href="{% url 'DataCrear' %}"> Crear Data</a>
</button>
</div>
</body>
</html>

AppCoder/templates/appcoder/editarPerfil.html
{% extends "AppCoder/padre.html" %}
{% load static %}


{% block titulo %}
<h1>Editar User Django<h1>

    <form action="" method="POST"> {% csrf_token %}
        
            
            {{formulario.as_p}}




       <div> 
        <input type="submit" value= "Editar">
       </div>
 </form>

{% endblock %}

{% block titulo2 %}



{% block descripcion %} 

<form action="/AppCoder/resultados/" method="GET"> {% csrf_token %}

    <h2> Busqueda </h2>
   <input type="text" name = "email" id ="email" >
  
    <input type="submit" value= "Buscar">

</form> 

{% endblock %}


<p>Estamos buscando: {{email}} </p>

{% for x in datos %}
    <p> Nombre: {{x.nombre}} --- Email: {{x.email}} ---- Phone: {{x.phone}} ---- Imagen: {{x.imagen}} </p>
{% endfor %}


{% endblock %}

AppCoder/templates/appcoder/login.html
{% extends "AppCoder/padre.html" %}
{% load static %}


{% block titulo %}
<h1>Inicia sesion<h1>

    <form action="" method="POST"> {% csrf_token %}
        
            
            {{formulario.as_p}}




       <div> 
        <input type="submit" value= "Inicia sesión">
       </div>
 </form>

{% endblock %}

{% block titulo2 %}



{% block descripcion %} 

<form action="/AppCoder/resultados/" method="GET"> {% csrf_token %}

    <h2> Busqueda </h2>
   <input type="text" name = "email" id ="email" >
  
    <input type="submit" value= "Buscar">

</form> 

{% endblock %}


<p>Estamos buscando: {{email}} </p>

{% for x in datos %}
    <p> Nombre: {{x.nombre}} --- Email: {{x.email}} ---- Phone: {{x.phone}}  </p>
{% endfor %}


{% endblock %}

AppCoder/templates/appcoder/logout.html
{% extends "AppCoder/padre.html" %}
{% load static %}


{% block titulo %}
<h1>Cerraste Sesión {{mensaje}}!<h1>

    <form action="/AppCoder/formu1/" method="POST"> {% csrf_token %}
        <table>
            
            {{form1.as_table}}




        </table>
       <div> 
        
       </div>
 </form>

{% endblock %}

{% block titulo2 %}



{% block descripcion %} 

<form action="/AppCoder/resultados/" method="GET"> {% csrf_token %}

    <h2> Busqueda </h2>
   <input type="text" name = "email" id ="email" </p>
  
    <input type="submit" value= "Buscar">

</form> 

{% endblock %}


<p>Estamos buscando: {{email}} </p>

{% for x in datos %}
    <p> Nombre: {{x.nombre}} --- Email: {{x.email}} ---- Phone: {{x.phone}}  </p>
{% endfor %}


{% endblock %}

AppCoder/templates/appcoder/registro.html
{% extends "AppCoder/padre.html" %}
{% load static %}


{% block titulo %}
<h1>Registrate<h1>

    <table>
    <form action="" method="POST"> {% csrf_token %}
        <table>
            
            {{formulario.as_table}}




    
        
    </table>
    <button type="submit" > Registrate </button>
 </form>
</table>


{% endblock %}

{% block titulo2 %}



{% block descripcion %} 

<form action="/AppCoder/resultados/" method="GET"> {% csrf_token %}

    <h2> Busqueda </h2>
   <input type="text" name = "email" id ="email" >
  
    <input type="submit" value= "Buscar">

</form> 

{% endblock %}


<p>Estamos buscando: {{email}} </p>

{% for x in datos %}
    <p> Nombre: {{x.nombre}} --- Email: {{x.email}} ---- Phone: {{x.phone}}  </p>
{% endfor %}


{% endblock %}